group: travis_latest
dist: xenial  # Travis CI's default distro
language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
    include:
        - python: 3.6
          env: TOX_ENV=py36
        - python: 3.7
          env: TOX_ENV=py37
install:
    - pip install -r test_requirements.txt
before_script:
    # run black to check if some files would need reformatting
    - black --check . || true
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    # Check python install package
    - pip install -e .
    - tox -e $TOX_ENV
    # Check python uninstall package
    - pip uninstall -y algorithms
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
