language: shell
dist: xenial
os: linux

jobs:
  include:
    -
      language: node_js
      node_js:
        - 14
      before_script:
        - npm install -g free-programming-books-lint
      script:
        - fpb-lint ./books/
        - fpb-lint ./casts/
        - fpb-lint ./courses/
        - fpb-lint ./more/
