language: ruby
rvm:
  - 2.2

before_script:
  - bundle
  - chmod +x ci_script.sh

script: ./ci_script.sh

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
