name: "Run tests"

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FORMAT_FILE: README.md

jobs:
  test:
    name: 'Validate README.md'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Markdown format
        run: build/validate_format.py ${FORMAT_FILE}

      - name: Validate pull request changes
        run: build/github-pull.sh ${{ github.repository }} ${{ github.event.pull_request.number }} ${FORMAT_FILE}
        if: github.event_name == 'pull_request'
