pull_request_rules:
  - name: Automatic merge on approval and successful build
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=build
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
        strict_method: merge
      delete_head_branch: {}
