language: ruby
node_js:
  - "node"
rvm:
  - 2.2
env:
  - TRAVIS_NODE_VERSION="7"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
before_script:
  - gem install awesome_bot
  - npm install --global awesome-lint
script:
  - awesome-lint
  - awesome_bot README.md --white-list $(paste -d, -s white_listed_sites.txt) --allow-ssl --allow-redirect
