language: ruby
rvm:
    - 2.6.0
before_script:
    - gem install awesome_bot
script:
    - awesome_bot README.md --allow-dupe --white-list stackoverflow.com,youtube.com,igor.io,toranproxy.com,laravel-china.org,drupal.org,phpindonesia.id,packagist.in,getcomposer.org,php.cnpkg.org
notifications:
    email: false
