arch: amd64
os: linux
dist: focal
language: shell
services:
  - docker
before_script:
  - docker pull dkhamsing/awesome_bot:1.19.1-docker
  - docker pull silex/emacs:27.1-alpine
  - export AWESOME_BOT="docker run -ti --rm -v $(pwd):$(pwd) -w $(pwd) dkhamsing/awesome_bot:1.19.1-docker"
  - export EMACS="docker run -ti --rm -v $(pwd):$(pwd) -w $(pwd) silex/emacs:27.1-alpine emacs"
script:
  - allowed_internal_links=ternjs,melpa
  - allowed_redirect_links=awesome.re
  - $AWESOME_BOT README.org --allow-ssl --white-list $allowed_internal_links,$allowed_redirect_links
  - cp README.org README.org.original
  - diff README.org README.org.original
  - $EMACS --version
  - $EMACS README.org -Q -batch --eval "(progn (setq package-archives '((\"melpa\" . \"https://melpa.org/packages/\"))) (package-initialize) (when (not (package-installed-p 'toc-org)) (when (not package-archive-contents) (package-refresh-contents)) (package-install 'toc-org)) (require 'toc-org) (toc-org-insert-toc) (save-buffer))"
  - diff README.org README.org.original
  - echo "If the README pre and post processing are identical, the diff should exit with 0. Otherwise, an error code indicates that toc-org should have been run to update the Table of Contents."
notifications:
  email:
    on_success: never
    on_failure: never
