language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --white-list facebook.com,linkedin.com,quora.com,travis-ci.org,reddit.com,img.shields.io
