site_name: Awesome DTrace
site_url: https://www.awesome-dtrace.com
site_description: A curated list of awesome DTrace books, articles, videos, tools and resources.
site_author: Adam Števko
repo_url: https://github.com/xen0l/awesome-dtrace
google_analytics: ["UA-78808832-1", "auto"]
theme: yeti
pages:
  - "DTrace": "index.md"
