language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-ssl --allow-redirect --white-list github.com/sindresorhus/awesome,booleans.io,devnull-as-a-service.com
