language: ruby
rvm: 2.2
before_script: gem install awesome_bot
script: awesome_bot --allow-redirect --allow-ssl --allow 301,302 --white-list www.startupranking.com,angel.co,creativecommons.org/publicdomain/zero/1.0,www.crunchbase.com/#/home/index README.md
